# Generated by Django 4.2.16 on 2024-09-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmersManagement',
            fields=[
                ('farmer_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cooperative_number', models.SmallIntegerField(unique=True)),
                ('sacco_name', models.CharField(max_length=20)),
            ],
        ),
    ]
