# Generated by Django 4.2.16 on 2024-09-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_alter_farmersmanagement_cooperative_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmersmanagement',
            name='farmer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
