# Generated by Django 5.1.1 on 2024-09-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
