# Generated by Django 5.1.1 on 2024-09-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_alter_score_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='farmer',
            new_name='farmer_id',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='status',
            new_name='is_eligible',
        ),
    ]
