# Generated by Django 4.2.16 on 2024-11-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owns_car",
                    models.CharField(choices=[("Y", "Yes"), ("N", "No")], max_length=1),
                ),
                (
                    "owns_property",
                    models.CharField(choices=[("Y", "Yes"), ("N", "No")], max_length=1),
                ),
                ("num_children", models.IntegerField()),
                ("total_income", models.FloatField()),
                (
                    "education_type",
                    models.CharField(
                        choices=[
                            (
                                "Secondary / secondary special",
                                "Secondary / secondary special",
                            ),
                            ("Higher education", "Higher education"),
                            ("Incomplete higher", "Incomplete higher"),
                            ("Lower secondary", "Lower secondary"),
                            ("Academic degree", "Academic degree"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "family_status",
                    models.CharField(
                        choices=[
                            ("Married", "Married"),
                            ("Single / not married", "Single / not married"),
                            ("Civil marriage", "Civil marriage"),
                            ("Widow", "Widow"),
                            ("Separated", "Separated"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "housing_type",
                    models.CharField(
                        choices=[
                            ("Rented apartment", "Rented apartment"),
                            ("House / apartment", "House / apartment"),
                            ("Municipal apartment", "Municipal apartment"),
                            ("With parents", "With parents"),
                            ("Co-op apartment", "Co-op apartment"),
                            ("Office apartment", "Office apartment"),
                        ],
                        max_length=100,
                    ),
                ),
                ("age", models.IntegerField()),
                ("employment_duration", models.IntegerField()),
                (
                    "occupation_type",
                    models.CharField(
                        choices=[
                            ("Laborers", "Laborers"),
                            ("Core staff", "Core staff"),
                            ("Sales staff", "Sales staff"),
                            ("Managers", "Managers"),
                            ("Drivers", "Drivers"),
                            ("High skill tech staff", "High skill tech staff"),
                            ("Accountants", "Accountants"),
                            ("Medicine staff", "Medicine staff"),
                        ],
                        max_length=100,
                    ),
                ),
                ("number_of_family_members", models.IntegerField()),
                ("total_dependents", models.IntegerField()),
                ("household_size", models.IntegerField()),
                ("is_long_employment", models.BooleanField()),
                ("prediction_result", models.IntegerField(null=True)),
            ],
        ),
    ]
