# Generated by Django 5.1.1 on 2024-09-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0002_cooperative_user'),
        ('farmers', '0002_alter_farmersmanagement_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersmanagement',
            name='cooperative_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.cooperative'),
        ),
    ]
