# Generated by Django 4.2.16 on 2024-09-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecords',
            name='record_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
