# Generated by Django 5.1.1 on 2024-10-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0002_cooperative_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='cooperative_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
