# Generated by Django 5.1.1 on 2024-09-19 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('credit_score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.SmallIntegerField()),
                ('credit_worthiness', models.CharField(max_length=20)),
                ('loan_range', models.CharField(max_length=50)),
                ('last_checked_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmersmanagement')),
            ],
        ),
    ]
