# Generated by Django 4.2.16 on 2024-09-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkRecords',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('milk_quantity', models.SmallIntegerField()),
                ('price', models.SmallIntegerField()),
                ('date', models.DateField()),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='farmers.farmersmanagement')),
            ],
        ),
    ]
