# Generated by Django 4.2.16 on 2024-11-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milkrecords", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milkrecords",
            name="price",
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=10),
        ),
    ]
