# Generated by Django 4.2.16 on 2024-11-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milkrecords", "0002_alter_milkrecords_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milkrecords",
            name="price",
            field=models.SmallIntegerField(default=70),
        ),
    ]
