# Generated by Django 4.2.16 on 2024-11-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milkrecords", "0003_alter_milkrecords_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milkrecords",
            name="milk_quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="milkrecords",
            name="price",
            field=models.IntegerField(default=70),
        ),
    ]
