# Generated by Django 4.2.16 on 2024-11-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("milkrecords", "0002_alter_milkrecords_milk_quantity_and_more"),
        ("milkrecords", "0003_alter_milkrecords_price"),
    ]

    operations = []
