
# Generated by Django 4.2.16 on 2024-11-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("milkrecords", "0004_alter_milkrecords_milk_quantity_and_more"),
        ("milkrecords", "0005_alter_milkrecords_milk_quantity_and_more"),
    ]

    operations = []
