# Generated by Django 4.2.16 on 2024-11-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milkrecords", "0006_merge_20241118_1606"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milkrecords",
            name="milk_quantity",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="milkrecords",
            name="price",
            field=models.SmallIntegerField(default=70),
        ),
    ]
